# Generated by Django 5.2.18 on 2026-10-08 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaConversion',
            fields=[
                ('id_regla', models.AutoField(primary_key=True, serialize=False)),
                ('puntos_por_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vigente_desde', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=150)),
                ('peso_estimado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('franja_horaria', models.CharField(max_length=30)),
                ('codigo_qr', models.CharField(max_length=64, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADA', 'Asignada'), ('RECOLECTADA', 'Recolectada'), ('CANCELADA', 'Cancelada')], max_length=20)),
                ('fecha_solicitud', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=120, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=150)),
                ('rol', models.CharField(choices=[('GENERADOR', 'Generador'), ('RECOLECTOR', 'Recolector'), ('ADMINISTRADOR', 'Administrador')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RutaParada',
            fields=[
                ('id_parada', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('ruta', models.ForeignKey(db_column='id_ruta', on_delete=django.db.models.deletion.PROTECT, to='core.ruta')),
                ('solicitud', models.OneToOneField(db_column='id_solicitud', on_delete=django.db.models.deletion.PROTECT, to='core.solicitud')),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='generador',
            field=models.ForeignKey(db_column='id_generador', on_delete=django.db.models.deletion.PROTECT, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='recolector',
            field=models.ForeignKey(db_column='id_recolector', on_delete=django.db.models.deletion.PROTECT, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Recoleccion',
            fields=[
                ('id_recoleccion', models.AutoField(primary_key=True, serialize=False)),
                ('peso_real', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_hora', models.DateTimeField()),
                ('solicitud', models.OneToOneField(db_column='id_solicitud', on_delete=django.db.models.deletion.PROTECT, to='core.solicitud')),
                ('recolector', models.ForeignKey(db_column='id_recolector', on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoPuntos',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ACUMULA', 'Acumula'), ('REDIME', 'Redime')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('recibo', models.ForeignKey(blank=True, db_column='id_recibo', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.recibo')),
                ('recoleccion', models.OneToOneField(blank=True, db_column='id_recoleccion', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.recoleccion')),
                ('regla', models.ForeignKey(blank=True, db_column='id_regla', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.reglaconversion')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
            ],
        ),
    ]
